### ISSUE TITLE
Email sanitizer removes dots

### ISSUE THREAD

**Issue by Baterka** [53js/ajv-sanitizer#1]
```
properties: {
 email: {
  type: "string",
  format: "email",
  sanitize: 'email',
 },
 }
```
For input `test.test@gmail.com` I am getting sanitized `testtest@gmail.com`!
I dont know how other email providers but GMail supports dots!

**Comment by Baterka** [comment]
I created [pull request](https://github.com/53js/ajv-sanitizer/pull/2)

**Comment by hugomallet** [comment]
Hi @Baterka ,

The library exposes some sanitizers functions from the library [validator.js](https://www.npmjs.com/package/validator) as default.

The normalizeEmail sanitizer of validator.js removes by default dots in gmail addresses because gmail does not treats dots in addresses. So for gmail the emails testtest@gmail.com and test.test@gmail.com are considered the same addresses.

This is the default behavior.

The goal of this library is not to provide every options of validator.js as unique validators. If you need a specific behavior, you can set a sanitize function in your schema instead of a string.

For example in your case:
```js
import { normalizeEmail } from 'validator';

const schema = {
	type: 'object',
	properties: {
		value: {
			type: 'string',
			sanitize: value => normalizeEmail(value, { gmail_remove_dots: false }),
		},
	},
};
```

I'm looking to add a feature that would allow to add some validators globally to avoid repeating the sanitize function in every places in the schema. I'll let you know when available.

**Comment by hugomallet** [comment]
From version v1.1.1 you can override globally sanitizers :
```js
const Ajv = require('ajv');
const ajvSanitizer = require('ajv-sanitizer');
const { normalizeEmail } = require('validator');
 
const ajv = new Ajv();
const extraSanitizers = {
    email: email => normalizeEmail(email, { gmail_remove_dots: false }), // overrides default email sanitizer
};
 
ajvSanitizer(ajv, extraSanitizers);
```
